language: go
go:
  - 1.3
  - 1.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq liblzma-dev

install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/appc/spec/discovery
  - go get github.com/apcera/logray

script:
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...
